name: GeorgeCuevas
favicon: null
layout_spectrum: 0.2562
typography_spectrum: 0.31285
title: TheWorks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#000000'
    - '#b9b9b9'
    - '#3e3d42'
    - '#74747c'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
