name: GeorgeCuevas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75347
title: TheWorks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cacccb'
    - '#111520'
    - '#ab8776'
    - '#f6f7f9'
    - '#604639'
  brandStrength: 0.5625
  lightness: 0.3614605616312474
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
